{{- if .Values.podDisruptionBudget.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: continuum-api-pdb
  namespace: {{ .Values.global.namespace }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app: continuum-api

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: continuum-web-pdb
  namespace: {{ .Values.global.namespace }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: continuum-web
{{- end }}
