apiVersion: v1
kind: Secret
metadata:
  name: continuum-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    app: continuum
type: Opaque
stringData:
  databaseUrl: "{{ .Values.secrets.databaseUrl }}"
  {{- if .Values.secrets.awsAccessKeyId }}
  awsAccessKeyId: "{{ .Values.secrets.awsAccessKeyId }}"
  {{- end }}
  {{- if .Values.secrets.awsSecretAccessKey }}
  awsSecretAccessKey: "{{ .Values.secrets.awsSecretAccessKey }}"
  {{- end }}
  {{- if .Values.secrets.s3Bucket }}
  s3Bucket: "{{ .Values.secrets.s3Bucket }}"
  {{- end }}
  {{- if .Values.secrets.slackWebhookUrl }}
  slackWebhookUrl: "{{ .Values.secrets.slackWebhookUrl }}"
  {{- end }}
